### PR TITLE
Fixed typo in README.md, missing /config from install path

### PR DESCRIPTION
**Pull request by mattisdada**

### CODE REVIEW

**Comment by daylerees** [comment]
Hey @mattisdada , what's your OS? I don't have `config` on OSX, it's just in the WebIde100 dir.

**Comment by mattisdada** [comment]
Huh, I would have assumed it would be the same cross platform. But that was the directory for Windows. Same structure from .Webide60 - .Webide110

**Comment by daylerees** [comment]
@mattisdada wanna change the PR to say  something like on windows: xxx and on unix-based platforms : xxx ?

It sounds simple, but I think it would help a bunch of people. :)

**Comment by mattisdada** [comment]
Yeah sure will

**Comment by cwhite92** [comment]
Just did this on Ubuntu, for reference the colours directory on linux platforms seems to be: `./WebIde100/config/colors`

**Comment by daylerees** [comment]
Must just be OSX that's different. :)

**Pull request closed without merging**
